### ISSUE TITLE
Use Vapor JWT and cache public tokens

### ISSUE THREAD

**Issue by sidmani** [ncvitak/FireVerify#1]
Hi, I thought you might be interested in a few improvements I made to your code.
1) I modified the keychain to use asynchronous requests
2) It now caches the public keys and uses the cache until they expire (as per the max-age)
3) Uses Vapor/JWT instead, which I felt would allow less dependencies considering that most server-side swift depends on Vapor anyway.

I didn't submit a pull request because I modified the code with my project in mind, but [here's the link to my fork.](https://github.com/sidmani/FireVerify)

**Comment by ncvitak** [comment]
Hey Thanks!
I was going to implement the caching myself, but I've been really busy with school lately.

As per using Vapor/JWT, my JWT library was only supposed to be temporary anyways. At the time Vapor's JWT library had a serious bug, which is now probably fixed.

Feel free to submit a pull request.
